/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AccordionThree: typeof import('./src/components/AccordionThree.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CustomDataTable: typeof import('./src/components/DataTable/CustomDataTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableComponent: typeof import('./src/components/DataTable/DataTableComponent.vue')['default']
    Details: typeof import('./src/components/Products/Details.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterConfiguratorTable: typeof import('./src/components/FilterConfigurator/FilterConfiguratorTable.vue')['default']
    FilterConfiguratorWrapper: typeof import('./src/components/FilterConfigurator/FilterConfiguratorWrapper.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer/NavigationDrawer.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Password: typeof import('primevue/password')['default']
    PopupFormComponent: typeof import('./src/components/PopupFormComponent.vue')['default']
    ProductDetails: typeof import('./src/components/Products/ProductDetails.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    TestForm: typeof import('./src/components/TestForm.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
}
