/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionComponent: typeof import('./src/components/AccordionComponent.vue')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AccordionThree: typeof import('./src/components/AccordionThree.vue')['default']
    AccordionWrapper: typeof import('./src/components/AccordionWrapper.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    CustomDataTable: typeof import('./src/components/DataTable/CustomDataTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterConfiguratorTable: typeof import('./src/components/FilterConfigurator/FilterConfiguratorTable.vue')['default']
    FilterConfiguratorWrapper: typeof import('./src/components/FilterConfigurator/FilterConfiguratorWrapper.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer/NavigationDrawer.vue')['default']
    Password: typeof import('primevue/password')['default']
    PopupFormComponent: typeof import('./src/components/PopupFormComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestForm: typeof import('./src/components/TestForm.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TreeTable: typeof import('primevue/treetable')['default']
  }
}
